# Generated by Django 4.0 on 2021-12-11 22:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='crops/')),
                ('crop_type', models.CharField(blank=True, choices=[('Cereal', 'Cereal'), ('Grain', 'Grain'), ('Tuber', 'Tuber'), ('Fruit', 'Fruit'), ('Cash', 'Cash Crop'), ('Vegetable', 'Vegetable')], max_length=150, null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crops', to='auth.user')),
            ],
            options={
                'db_table': 'crops',
                'ordering': ['description', 'crop_type'],
            },
        ),
    ]
