# Generated by Django 4.0 on 2021-12-11 22:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crop', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('unit', models.CharField(blank=True, choices=[('Basket', 'Basket'), ('Sack', 'Sack'), ('Kilogram', 'Kilogram'), ('Ton', 'Ton'), ('Barn', 'Barn')], max_length=10, null=True)),
                ('season', models.IntegerField(blank=True, choices=[(1, 'Main Season'), (2, 'Lean Season')], null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvests', to='auth.user')),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvest_crop', to='crop.crop')),
            ],
            options={
                'db_table': 'harvest',
                'ordering': ['date'],
            },
        ),
    ]
